Create database `Politico`CHARSET = UTF8 COLLATE = utf8_general_ci; 

Use Politico;

CREATE TABLE Usuario(
`ID_Usuario` INT NOT NULL AUTO_INCREMENT,
`Nome` VARCHAR (100) NOT NULL,
`Email` VARCHAR (100) NOT NULL,
`Senha` VARCHAR (100) NOT NULL,
`Cpf` VARCHAR (20) NOT NULL,

CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
CONSTRAINT UK_USUARIO_CPF UNIQUE (Cpf),
CONSTRAINT UK_USUARIO_EMAIL UNIQUE (Email)
)
ENGINE = InnoDB;

select * from usuario;